---
title: Oxfordshire <br/>Community <br/>Land Trust
gcaptcha: 6LdNn1AUAAAAAA-VLy7CCzufqQi7EhPyoWQwcHIM
source: "."
destination: "./_site"
plugins_dir: _plugins
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
collections:
  posts:
    output: true
  pages:
    output: true
    permalink: "/:title/index.html"
  projects:
    output: true
    permalink: "/projects/:title/index.html"
  faqs:
    output: false
defaults: []
safe: false
include:
- ".htaccess"
- _pages
exclude:
- node_modules/
- package-lock.json
- package.json
- webpack.mix.js
- yarn.lock
- readme.md
- shipitfile.js
- Gemfile
- Gemfile.lock
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
strict_front_matter: false
whitelist: []
plugins:
- jekyll-feed
- jekyll-seo-tag
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
detach: false
port: 4000
host: 127.0.0.1
baseurl: "/"
show_dir_listing: false
permalink: date
paginate_path: "/page:num"
timezone: Etc/UTC
quiet: false
verbose: true
liquid:
  error_mode: warn
rdiscount:
  extensions: []
redcarpet:
  extensions: []
kramdown:
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM
  hard_wrap: false
  footnote_nr: 1
  show_warnings: false
