title: Oxfordshire <br/>Community <br/>Land Trust
email: john@jdp.org.uk
description: |
  Site description from config
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.url.com" # the base hostname & protocol for your site, e.g. http://example.com
footer: |
  Oxfordshire Community Land Trust is the trading name of OCLT Ltd,
  registered as an Industrial and Provident Society for the benefit of the
  community under the Industrial and Provident Societies Act 1965.

  FSA Registration: 30158R

  55 Henley Avenue, Oxford, OX4 4DJ
social:
  - twitter: OxfordshireCLT
  - facebook: oxfordshireclt
date_format: "%d.%m.%y "