---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: "./_pages"
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: "./_projects"
  label: Projects
  create: all
  match: "**/*"
- type: directory
  path: "./_faqs"
  label: Faqs
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
