---
label: project
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: excerpt
  label: Excerpt
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: true
  default: project
  config:
    required: true
