---
label: project
hide_body: 
is_partial: 
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: excerpt
  label: Excerpt
  type: text
  hidden: false
  default: ''
- name: layout
  label: Layout
  type: text
  hidden: false
  default: ''
